### ISSUE TITLE
How to force compiling even without request for .css file?

### ISSUE THREAD

**Issue by soaph** [emberfeather/less.js-middleware#135]
I just want to compile several `.less` files, and concatenate them with other `.css` file, then minify them.

But it seems that only when there is a request in .html file will less-middleware compile the `.less` file.

I wonder if there is any solution to my issue.?

Thanks very much.

**Comment by Zoramite** [comment]
If you are looking for a build step then you want to look into the more binary/build type of rules that would precompile the less files.

less-middleware is made to cache with the right options so that it is only generated once in production. If you just want to write the less and get the compiled/minified css then look into the [CLI usage of less](http://lesscss.org/#using-less-command-line-usage).
